---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels: 
    app: nginx-pod
    type: website


spec: 
  containers:
    - name: nginx-container
      image: nginx
      
#
# make sure you pull the docker image "docker pull ImageName"
#
# create the pod with "kubectl create -f file-name"
#
# check for new pod with "kubectl get pods"
#
# get more information about the pod with "kubectl describe pods pod-name" from the 'name:' part
#
# alidate and Verify your YAML documents, http://www.yamllint.com/