---
apiVersion: v1
kind: Pod
metadata: 
  name: ngnix-pod
  labels: 
    app: ngnix
    type: ngnix-web

spec: 
  containers:
    - name: ngix-container
      image: ngnix

---
apiVersion: v1
kind: Pod
metadata: 
  name: jenkins-pod
  labels: 
    app: jenkins-pod
    type: jenkins-web    

spec: 
  containers:
    - name: jenkins-container
      image: jenkins