---
apiVersion: v1
kind: Service
metadata:
    name: nginx-loadbalancer
    
spec:
    type: LoadBalancer
    selector:
       type: frontend
    ports:
      - port: 80            # the kubernetes service port
        targetPort: 30012   # the node port, external kubernetes access
