---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv
  namespace: jenkins-namespace
  
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-pv-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/sharedfolder/jenkins
    server: 192.168.50.79
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins-namespace
  
spec:
  storageClassName: jenkins-pv-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi