---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistentvolumeclaim-nfs
spec:
  storageClassName: jenkins-persistentvolume-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi