---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-persistentvolume-nfs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-persistentvolume-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/sharedfolder/jenkins
    server: 192.168.50.79
    readOnly: false
